# Generated by Django 3.0.1 on 2019-12-22 03:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('byline', models.CharField(max_length=200)),
                ('short_bio', models.TextField()),
                ('long_bio', models.TextField()),
                ('small_avatar_url', models.URLField()),
                ('large_avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=500)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('featured_image', models.URLField()),
                ('promo', models.TextField()),
                ('headline', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('disclosure', models.TextField()),
                ('publish_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fool.Author')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fool.Bureau')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fool.Pitch')),
                ('quotes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fool.Quote')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fool.Tag')),
            ],
        ),
    ]
